server:
  port:8090

logging:
  level:
    root: info
  config: classpath:log/logback.xml

spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    streams:
      state:
        dir: ./state-dir
